//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.13 at 12:11:50 PM CET 
//


package es.uji.apps.cvn.ui.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CvnBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CvnBean">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CvnBean", propOrder = {
    "code"
})
@XmlSeeAlso({
    CvnEntityBean.class,
    CvnDuration.class,
    CvnDateYear.class,
    CvnTitleBean.class,
    CvnDateMonthYear.class,
    CvnString.class,
    CvnPhoneBean.class,
    CvnPageBean.class,
    CvnAuthorBean.class,
    CvnDouble.class,
    CvnFamilyNameBean.class,
    CvnBoolean.class,
    CvnDateDayMonthYear.class,
    CvnVolumeBean.class,
    CvnPhotoBean.class,
    CvnExternalPKBean.class,
    CvnItemBean.class
})
public class CvnBean {

    @XmlElement(name = "Code")
    protected String code;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
