//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.13 at 12:11:50 PM CET 
//


package es.uji.apps.cvn.ui.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CvnAuthorBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CvnAuthorBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://codes.cvn.fecyt.es/beans}CvnBean">
 *       &lt;sequence>
 *         &lt;element name="CvnFamilyNameBean" type="{http://codes.cvn.fecyt.es/beans}CvnFamilyNameBean" minOccurs="0"/>
 *         &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SignatureOrder" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CvnLanguageBean", propOrder = {
    "languageName",
    "languageCode"
})
public class CvnLanguage
    extends CvnBean
{

    @XmlElement(name = "LanguageName")
    private String languageName;
    @XmlElement(name = "LanguageCode")
    private String languageCode;

    String getLanguageCode() {
        return languageCode;
    }

    void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    String getLanguageName() {
        return languageName;
    }

    void setLanguageName(String languageName) {
        this.languageName = languageName;
    }


    public void setName(String languageName) {
        this.languageName = languageName;
    }

    public void setCountry(String languageCode) {
        this.languageCode = languageCode;
    }
}
