//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.13 at 12:11:50 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://codes.cvn.fecyt.es/beans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.uji.apps.cvn.ui.beans;
